### ISSUE TITLE
Snippet Broadcast not work

### ISSUE THREAD

**Issue by zephiro** [aweber/AWeber-API-Python-Library#30]
https://labs.aweber.com/snippets/broadcasts

#!/usr/bin/env python
# -*- coding: utf-8-*-
 
from requests_oauthlib import OAuth1
 
# Insert account_id and list_id
account_id = XXXXXX
list_id = XXXXXX
 
#  Insert consumer key & consumer secret
consumer_key = 'XXXXXXXXXXXXXXXXXXXXX'
consumer_secret = 'XXXXXXXXXXXXXXXXXXXXX'
 
#  Insert access token & access secret
access_token = "XXXXXXXXXXXXXXXXXXXXX"
access_secret = "XXXXXXXXXXXXXXXXXXXXX"
 
headers = {'Content-Type': 'application/x-www-form-urlencoded'}
 
auth = OAuth1(consumer_key,
    client_secret=consumer_secret,
    resource_owner_key=access_token,
    resource_owner_secret=access_secret,
    signature_type='query'
)
 
body = {
    'click_tracking_enabled': True,
    'is_archived': True,
    'notify_on_send': True,
    'body_text': 'BROADCAST PLAIN TEXT VERSION',
    'body_html': '<html><head><body>This is my html</body></head></html>',
    'subject': 'BROADCAST SUBJECT',
}
 
url = 'https://api.aweber.com/1.0/accounts/{0}/lists/{1}/broadcasts'.format(account_id, list_id)
request = requests.post(url, auth=auth, data=body, headers=headers)

shows no errors but do not add

**Comment by amberheilman** [comment]
Please add to the top:
import requests

Please append to the bottom:
print request.content

That will display the content of the response.

You must also add your consumer keys, access keys, account id and list id to the indicated spot in the script.
